### ISSUE TITLE
Creating snapshot on KVM seems to block router operations

### ISSUE THREAD

**Issue by remibergsma** [MissionCriticalCloud/cosmic#12]
This snapshot job was created, sequence: `4494310953139132674`:

```
2016-06-22 16:02:20,341 DEBUG [c.c.a.t.Request] (API-Job-Executor-71:ctx-a83500fc job-173319 ctx-f3446e61) Seq 195-4494310953139132674: Sending  { Cmd , MgmtId: 2886730125, via: 195(hypervisor), Ver: v1, Flags: 100111, [{"org.apache.cloudstack.storage.command.CopyCommand":{"srcTO":{"org.apache.cloudstack.storage.to.SnapshotObjectTO":{"path":"/mnt/a8b493fe-7f50-3435-9bd0-61899d6ad490/60ad938a-afc8-4a50-be80-25bd950a4d41/f7391fd7-7881-43b0-a714-e5ae4287a83b","volume":{"uuid":"60ad938a-afc8-4a50-be80-25bd950a4d41","volumeType":"DATADISK","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"a8b493fe-7f50-3435-9bd0-61899d6ad490","id":39,"poolType":"NetworkFilesystem"
<cut>
```

Other operations (like spinning a VM) are waiting for that:

```
2016-06-22 21:57:25,912 DEBUG [o.a.c.n.t.BasicNetworkTopology] (Work-Job-Executor-15:ctx-ce669ba8 job-174279/job-174282 ctx-bd5226e9) Applying dhcp entry in network Ntwk[1189|Guest|52]
```

```
2016-06-22 21:57:25,946 DEBUG [c.c.a.t.Request] (Work-Job-Executor-15:ctx-ce669ba8 job-174279/job-174282 ctx-bd5226e9) Seq 195-4494310953139145246: Waiting for Seq 4494310953139132674 Scheduling:  { Cmd , MgmtId: 2886730125, via: 19
5(hypervisor), Ver: v1, Flags: 100111, [{"com.cloud.agent.api.routing.DhcpEntryCommand":{"vmMac":"02:00:77:5e:00:03","vmIpAddress":"10.136.252.92","vmName":"vmname134","defaultRouter":"10.136.252
.1","duid":"00:03:00:01:02:00:77:5e:00:03","isDefault":true,"executeInSequence":true,"accessDetails":{"router.name":"r-6047-VM","router.guest.ip":"10.136.252.1","router.ip":"169.254.2.26","zone.network.type":"Advanced"},"wait":0}}] 
}
```

```
2016-06-22 22:27:11,241 WARN  [o.a.c.f.j.i.AsyncJobMonitor] (Timer-1:ctx-ae52240f) Task (job-174282) has been pending for 1785 seconds
```

```
2016-06-22 22:27:25,947 DEBUG [c.c.a.m.AgentAttache] (Work-Job-Executor-15:ctx-ce669ba8 job-174279/job-174282 ctx-bd5226e9) Seq 195-4494310953139145246: Waited too long.
2016-06-22 22:27:25,947 INFO  [c.c.u.e.CSExceptionErrorCode] (Work-Job-Executor-15:ctx-ce669ba8 job-174279/job-174282 ctx-bd5226e9) Could not find exception: com.cloud.exception.OperationTimedoutException in error code list for exceptions
2016-06-22 22:27:25,947 WARN  [c.c.a.m.AgentAttache] (Work-Job-Executor-15:ctx-ce669ba8 job-174279/job-174282 ctx-bd5226e9) Seq 195-4494310953139145246: Timed out on Seq 195-4494310953139145246:  { Cmd , MgmtId: 2886730125, via: 195(hypervisor), Ver: v1, Flags: 100111, [{"com.cloud.agent.api.routing.DhcpEntryCommand":{"vmMac":"02:00:77:5e:00:03","vmIpAddress":"10.136.252.92","vmName":"vmtest134","defaultRouter":"10.136.252.1","duid":"00:03:00:01:02:00:77:5e:00:03","isDefault":true,"executeInSequence":true,"accessDetails":{"router.name":"r-6047-VM","router.guest.ip":"10.136.252.1","router.ip":"169.254.2.26","zone.network.type":"Advanced"},"wait":0}}] }
2016-06-22 22:27:25,948 DEBUG [c.c.a.m.AgentAttache] (Work-Job-Executor-15:ctx-ce669ba8 job-174279/job-174282 ctx-bd5226e9) Seq 195-4494310953139145246: Cancelling.
2016-06-22 22:27:25,948 WARN  [c.c.n.r.NetworkHelperImpl] (Work-Job-Executor-15:ctx-ce669ba8 job-174279/job-174282 ctx-bd5226e9) Timed Out
com.cloud.exception.OperationTimedoutException: Commands 4494310953139145246 to Host 195 timed out after 1800
        at com.cloud.agent.manager.AgentAttache.send(AgentAttache.java:429)
        at com.cloud.agent.manager.AgentManagerImpl.send(AgentManagerImpl.java:454)
        at com.cloud.agent.manager.AgentManagerImpl.send(AgentManagerImpl.java:972)
        at com.cloud.network.router.NetworkHelperImpl.sendCommandsToRouter(NetworkHelperImpl.java:165)
        at org.apache.cloudstack.network.topology.AdvancedNetworkVisitor.visit(AdvancedNetworkVisitor.java:87)
        at com.cloud.network.rules.DhcpEntryRules.accept(DhcpEntryRules.java:62)
        at org.apache.cloudstack.network.topology.BasicNetworkTopology.applyRules(BasicNetworkTopology.java:391)
        at org.apache.cloudstack.network.topology.AdvancedNetworkTopology.applyDhcpEntry(AdvancedNetworkTopology.java:173)
        at com.cloud.network.element.VirtualRouterElement.addDhcpEntry(VirtualRouterElement.java:938)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareElement(NetworkOrchestrator.java:1113)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareNic(NetworkOrchestrator.java:1239)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepare(NetworkOrchestrator.java:1175)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:907)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:4451)
        at sun.reflect.GeneratedMethodAccessor382.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:106)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:4607)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:555)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:503)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-06-22 22:27:25,949 WARN  [o.a.c.n.t.BasicNetworkTopology] (Work-Job-Executor-15:ctx-ce669ba8 job-174279/job-174282 ctx-bd5226e9) Unable to apply dhcp entry on disconnected router r-6047-VM
com.cloud.exception.AgentUnavailableException: Resource [Host:195] is unreachable: Host 195: Unable to send commands to virtual router 
        at com.cloud.network.router.NetworkHelperImpl.sendCommandsToRouter(NetworkHelperImpl.java:168)
        at org.apache.cloudstack.network.topology.AdvancedNetworkVisitor.visit(AdvancedNetworkVisitor.java:87)
        at com.cloud.network.rules.DhcpEntryRules.accept(DhcpEntryRules.java:62)
        at org.apache.cloudstack.network.topology.BasicNetworkTopology.applyRules(BasicNetworkTopology.java:391)
        at org.apache.cloudstack.network.topology.AdvancedNetworkTopology.applyDhcpEntry(AdvancedNetworkTopology.java:173)
        at com.cloud.network.element.VirtualRouterElement.addDhcpEntry(VirtualRouterElement.java:938)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareElement(NetworkOrchestrator.java:1113)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareNic(NetworkOrchestrator.java:1239)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepare(NetworkOrchestrator.java:1175)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:907)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:4451)
        at sun.reflect.GeneratedMethodAccessor382.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

Why would this be blocking at all?

**Comment by bheuvel** [comment]
When looking at line [gentAttache.java#L357](https://github.com/MissionCriticalCloud/cosmic/blob/master/cosmic-core/engine/orchestration/src/main/java/com/cloud/agent/manager/AgentAttache.java#L357) ( with help from debugger :wink: )

```
if (req.executeInSequence() && _currentSequence != null) {
    req.logD("Waiting for Seq " + _currentSequence + " Scheduling: ", true);
    addRequest(req);
    return;
}
```

it seems that some tasks, such as createSnapshot or rebootVM, have the `executeInSequence()` set.

The "first" which has `executeInSequence()` set, will set `_currentSequence` to itself.
The next job which has `executeInSequence()` set (and asuming the first job did not yet finish, therefore `_currentSequence` is still set), will just add itself to a queue.

So if snapshot comes first, rebootvm will wait untill that is finished.

For example command `com.cloud.agent.api.GetHostStatsCommand` doesn't have this set, therefore IS executed during a snapshot (and shows up in the agent log).

Now trying to see how/where the createSnapshot gets this attribute.

**Comment by bheuvel** [comment]
Some more details;

Method `sendMessage()` in [RemoteHostEndPoint](https://github.com/MissionCriticalCloud/cosmic/blob/da7193f4777405cd242d8f79a672e931f65397e5/cosmic-core/engine/storage/default/src/main/java/org/apache/cloudstack/storage/RemoteHostEndPoint.java#L161) uses `getGuruProcessedCommandTargetHost` in [HypervisorGuruManagerImpl.java#L58](https://github.com/MissionCriticalCloud/cosmic/blob/ee373f063a0919585c4f802f9bbc5d92498895bd/cosmic-core/server/src/main/java/com/cloud/hypervisor/HypervisorGuruManagerImpl.java#L58) to loop over these gurus by calling their `getCommandHostDelegation`:

```
    @Override
    public long getGuruProcessedCommandTargetHost(final long hostId, final Command cmd) {
        for (final HypervisorGuru guru : _hvGuruList) {
            final Pair<Boolean, Long> result = guru.getCommandHostDelegation(hostId, cmd);
            if (result.first()) {
                return result.second();
            }
        }
        return hostId;
    }
```

The method `getCommandHostDelegation`, implemented in the gurus [KVMGuru](https://github.com/MissionCriticalCloud/cosmic/blob/ee373f063a0919585c4f802f9bbc5d92498895bd/cosmic-core/server/src/main/java/com/cloud/hypervisor/KVMGuru.java#L35), and same for [Ovm3](https://github.com/MissionCriticalCloud/cosmic/blob/ee373f063a0919585c4f802f9bbc5d92498895bd/cosmic-core/plugins/hypervisor/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3HypervisorGuru.java#L73) and [XenServer](https://github.com/MissionCriticalCloud/cosmic/blob/ee373f063a0919585c4f802f9bbc5d92498895bd/cosmic-core/plugins/hypervisor/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java#L72), calls `setExecuteInSequence(true)` (or not/false).

For the commands `CreateObjectCommand` and `CopyCommand` they return/set as follows when creating a snapshot:
- Ovm3Guru:  executeInSequence(true)
- KVMGuru: executeInSequence(false)
- XenServerGuru: executeInSequence(true)
  (Gurus processed in that specific order...)

So the KVMGuru seems to provide the "right" answer, but is not used!?

Reason for this seems to me that there might be a problem/omission in the implementation of the KVM guru; looking at the loop in the code here above of `getGuruProcessedCommandTargetHost` it will loop over all gurus (unless). In that case all gurus (re)setting the value in `cmd`, and XenServerGuru being the last one (--> executeInSequence(true)).

The loop will break (use/keep changes made by the guru that was just called) if the guru returned 
`true` in the `Pair<Boolean, Long> result`: **the KVM Guru never returns true!**

The KVMGuru should return true if _this_ concerns KVM.

(creating small code change now to check...)
